# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cocainate < Formula
  desc "Cross-platform caffeinate alternative."
  homepage "https://github.com/AppleGamer22/cocainate"
  version "1.0.13"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.13/cocainate_1.0.13_mac_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cdc37bd7753d92d093af145256cd1e0cc92c848cee68d04bcf5473c9656d9546"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.13/cocainate_1.0.13_mac_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a96474f4c9b01f380b9255a8c1cca627aa669c218b88fa5048876c305eff79e5"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.13/cocainate_1.0.13_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "502553bc4e7961ec527c2c2259f2b26104c9df8c9e1ee9559820a00fbf658c9f"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.13/cocainate_1.0.13_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6f9586387f363180765f40f2031f0cc94e51e124278ea82916673606708dc708"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
  end
end
