# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cocainate < Formula
  desc "Cross-platform caffeinate alternative."
  homepage "https://github.com/AppleGamer22/cocainate"
  version "1.0.17"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.17/cocainate_1.0.17_mac_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ea766b6abd3cbb3c04eb9ea339eaa1d511d4eef1d16ecc15560b7743feab8f4a"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.17/cocainate_1.0.17_mac_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "88120aeebec4d511f0ffff3c8df9f864a89a2afe59a7dd79d94da9986851d091"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.17/cocainate_1.0.17_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5e4bfb1dc5651485067dbd9c065a60770c4110bd1123b946256b058f3ca36ef0"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.17/cocainate_1.0.17_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "17702bde0f8f2e5eb149c6d36d9034d76422d633ab98e6029cbe4a718233175b"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
  end
end
