# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cocainate < Formula
  desc "Cross-platform caffeinate alternative."
  homepage "https://github.com/AppleGamer22/cocainate"
  version "1.0.14"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.14/cocainate_1.0.14_mac_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c13816adea995477de5ebca522e08eafca8e7b04282be9fa3ccdbc3694535c7d"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.14/cocainate_1.0.14_mac_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "68d595324b3c7bce33a39e20be65ccc076f84bfcfd1e2b4bc0afb9d21feba784"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.14/cocainate_1.0.14_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "094adafb255a56b147992a40051c90e4fa0128d81a76ad0bec5890d6b33d88a7"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AppleGamer22/cocainate/releases/download/v1.0.14/cocainate_1.0.14_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b4746ac98c502ac5b50eec088887f428a32906d917990b106d10c918e48efe94"

      def install
        bin.install "cocainate"
        man1.install "cocainate.1"
        bash_completion.install "cocainate.bash" => "cocainate"
        fish_completion.install "cocainate.fish"
        zsh_completion.install "cocainate.zsh" => "_cocainate"
      end
    end
  end
end
