# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stalk < Formula
  desc "Cross-platform file watcher."
  homepage "https://github.com/AppleGamer22/stalk"
  version "1.0.7"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/AppleGamer22/stalk/releases/download/v1.0.7/stalk_1.0.7_mac_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "66f45461cf7fae32bea7c505c71f29cbf71cca73ee10fc035d72a1c42d1e0e05"

      def install
        bin.install "stalk"
        man1.install "stalk.1"
        bash_completion.install "stalk.bash" => "stalk"
        fish_completion.install "stalk.fish"
        zsh_completion.install "stalk.zsh" => "_stalk"
      end
    end
    on_arm do
      url "https://github.com/AppleGamer22/stalk/releases/download/v1.0.7/stalk_1.0.7_mac_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6ee1846755ec9ec375c265413a3a5e1a553d981f0711d73a44acbd6e5562e100"

      def install
        bin.install "stalk"
        man1.install "stalk.1"
        bash_completion.install "stalk.bash" => "stalk"
        fish_completion.install "stalk.fish"
        zsh_completion.install "stalk.zsh" => "_stalk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AppleGamer22/stalk/releases/download/v1.0.7/stalk_1.0.7_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "67a1cf883fb8f6ba983f9ca37d30e290545c708f49bde7354e0a9b8f07519492"

        def install
          bin.install "stalk"
          man1.install "stalk.1"
          bash_completion.install "stalk.bash" => "stalk"
          fish_completion.install "stalk.fish"
          zsh_completion.install "stalk.zsh" => "_stalk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AppleGamer22/stalk/releases/download/v1.0.7/stalk_1.0.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "75c3afb5ac836f3be26015139b3d2754fab6788c8683186e77df78a2e022ea50"

        def install
          bin.install "stalk"
          man1.install "stalk.1"
          bash_completion.install "stalk.bash" => "stalk"
          fish_completion.install "stalk.fish"
          zsh_completion.install "stalk.zsh" => "_stalk"
        end
      end
    end
  end
end
