# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stalk < Formula
  desc "Cross-platform file watcher."
  homepage "https://github.com/AppleGamer22/stalk"
  version "1.0.3"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AppleGamer22/stalk/releases/download/v1.0.3/stalk_1.0.3_mac_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5efacfbff716b506d709f20925bfa5d54c50f9bba63e08fe39a7547924ea87dd"

      def install
        bin.install "stalk"
        man1.install "stalk.1"
        bash_completion.install "stalk.bash" => "stalk"
        fish_completion.install "stalk.fish"
        zsh_completion.install "stalk.zsh" => "_stalk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AppleGamer22/stalk/releases/download/v1.0.3/stalk_1.0.3_mac_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d7c42fc9dcaa8c3cb68b588c2696877b1b64533733c2b564f17e9a765a91591a"

      def install
        bin.install "stalk"
        man1.install "stalk.1"
        bash_completion.install "stalk.bash" => "stalk"
        fish_completion.install "stalk.fish"
        zsh_completion.install "stalk.zsh" => "_stalk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AppleGamer22/stalk/releases/download/v1.0.3/stalk_1.0.3_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5f1818f23ec9632b015cf617b2c2d2f23aa73a79ac8ce55a2e7999d7fb484455"

      def install
        bin.install "stalk"
        man1.install "stalk.1"
        bash_completion.install "stalk.bash" => "stalk"
        fish_completion.install "stalk.fish"
        zsh_completion.install "stalk.zsh" => "_stalk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AppleGamer22/stalk/releases/download/v1.0.3/stalk_1.0.3_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "631d5afe093ae616365aa46b8ab5003f56c7123ca169486fc77cfc7fa2f22b7b"

      def install
        bin.install "stalk"
        man1.install "stalk.1"
        bash_completion.install "stalk.bash" => "stalk"
        fish_completion.install "stalk.fish"
        zsh_completion.install "stalk.zsh" => "_stalk"
      end
    end
  end
end
